# Create a playbook using yum module to accomplish the task, here you can specify all those options which we can give with yum command.
# Reference URL: https://learningtechnix.wordpress.com/2019/03/15/ansible-case-study-automating-os-patching/
---
- name: RHEL7 system patching
  hosts: linux
  tasks:
  - name: yum to apply patches
     yum:
     name: '*'
     state: latest
     exclude: kernel*
     disablerepo: DVD, ansible
## end of patching code
ansible-playbook patching.yml
